-- ModularPhysics/Core/ClassicalMechanics.lean
-- Aggregator file for Classical Mechanics module

import ModularPhysics.PhysicsLogic.ClassicalMechanics.PhaseSpace
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Lagrangian
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Hamiltonian
import ModularPhysics.PhysicsLogic.ClassicalMechanics.CanonicalTransforms
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Constraints
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Symmetries
import ModularPhysics.PhysicsLogic.ClassicalMechanics.HamiltonJacobi
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Integrable
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Perturbation
import ModularPhysics.PhysicsLogic.ClassicalMechanics.Chaos
