-- Legacy aggregator file
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.Fields
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.Action
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.EulerLagrange
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.Noether
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.EnergyMomentum
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.Scalar
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.Electromagnetic
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.YangMills
import ModularPhysics.PhysicsLogic.ClassicalFieldTheory.Solitons
