/-
Copyright (c) 2025 ModularPhysics Contributors. All rights reserved.
Released under Apache 2.0 license.
Authors: ModularPhysics Contributors
-/
import Mathlib.Analysis.VonNeumannAlgebra.Basic
import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.InnerProductSpace.Projection.Basic
import Mathlib.Topology.Algebra.Module.WeakDual

/-!
# Von Neumann Algebras - Basic Theory

This file develops the basic theory of von Neumann algebras, building on Mathlib's
`VonNeumannAlgebra` and `WStarAlgebra` definitions.

We introduce:
- Cyclic vectors: vectors Ω such that M·Ω is dense in H
- Separating vectors: vectors Ω such that aΩ = 0 implies a = 0
- Cyclic-separating vectors for standard form

## Main definitions

* `VonNeumannAlgebra.IsCyclic` - predicate for cyclic vectors
* `VonNeumannAlgebra.IsSeparating` - predicate for separating vectors
* `VonNeumannAlgebra.IsCyclicSeparating` - predicate for cyclic and separating vectors
* `VonNeumannAlgebra.cyclicSubspace` - the closure of M·Ω

## Main results

* `VonNeumannAlgebra.separating_iff_cyclic_commutant` - Ω separating for M iff cyclic for M'

## References

* Takesaki, "Theory of Operator Algebras I"
* Bratteli-Robinson, "Operator Algebras and Quantum Statistical Mechanics"
-/

noncomputable section

open scoped InnerProduct ComplexConjugate

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

namespace VonNeumannAlgebra

variable (M : VonNeumannAlgebra H)

/-! ### Cyclic vectors -/

/-- The orbit of a vector under a von Neumann algebra -/
def orbit (Ω : H) : Set H :=
  { x : H | ∃ a ∈ M, a Ω = x }

/-- The cyclic subspace generated by Ω under M, i.e., the closure of M·Ω -/
def cyclicSubspace (Ω : H) : Submodule ℂ H :=
  Submodule.topologicalClosure (Submodule.span ℂ (M.orbit Ω))

/-- A vector Ω is cyclic for M if M·Ω is dense in H -/
def IsCyclic (Ω : H) : Prop :=
  M.cyclicSubspace Ω = ⊤

/-- A vector Ω is separating for M if aΩ = 0 implies a = 0 for all a ∈ M -/
def IsSeparating (Ω : H) : Prop :=
  ∀ a ∈ M, (a : H →L[ℂ] H) Ω = 0 → a = 0

/-- A vector is cyclic-separating if it is both cyclic and separating -/
def IsCyclicSeparating (Ω : H) : Prop :=
  M.IsCyclic Ω ∧ M.IsSeparating Ω

/-! ### Basic properties of cyclic vectors -/

theorem orbit_nonempty (Ω : H) : (M.orbit Ω).Nonempty := by
  use Ω
  exact ⟨1, M.toStarSubalgebra.one_mem, ContinuousLinearMap.one_apply Ω⟩

theorem zero_mem_orbit_of_zero : (0 : H) ∈ M.orbit (0 : H) := by
  exact ⟨0, M.toStarSubalgebra.zero_mem, map_zero 0⟩

theorem Ω_mem_orbit (Ω : H) : Ω ∈ M.orbit Ω := by
  exact ⟨1, M.toStarSubalgebra.one_mem, ContinuousLinearMap.one_apply Ω⟩

theorem orbit_subset_cyclicSubspace (Ω : H) : M.orbit Ω ⊆ M.cyclicSubspace Ω := fun _ hx =>
  (Submodule.span ℂ (M.orbit Ω)).le_topologicalClosure (Submodule.subset_span hx)

theorem Ω_mem_cyclicSubspace (Ω : H) : Ω ∈ M.cyclicSubspace Ω :=
  M.orbit_subset_cyclicSubspace Ω (M.Ω_mem_orbit Ω)

/-- The orbit is closed under the algebra action -/
theorem orbit_closed_under_action (Ω : H) (a b : H →L[ℂ] H) (ha : a ∈ M) (hb : b ∈ M)
    (_ : b Ω ∈ M.orbit Ω) : (a ∘L b) Ω ∈ M.orbit Ω := by
  exact ⟨a ∘L b, M.toStarSubalgebra.mul_mem ha hb, rfl⟩

/-- The cyclic subspace is M-invariant -/
theorem cyclicSubspace_invariant (Ω : H) (a : H →L[ℂ] H) (ha : a ∈ M) :
    ∀ x ∈ M.cyclicSubspace Ω, a x ∈ M.cyclicSubspace Ω := by
  intro x hx
  unfold cyclicSubspace at hx ⊢
  -- x is in the topological closure of span(M·Ω)
  -- Key: a maps orbit(Ω) into itself (actually into span)
  have h_orbit : ∀ y ∈ M.orbit Ω, a y ∈ Submodule.span ℂ (M.orbit Ω) := by
    intro y hy
    obtain ⟨b, hb, rfl⟩ := hy
    apply Submodule.subset_span
    exact ⟨a ∘L b, M.toStarSubalgebra.mul_mem ha hb, rfl⟩
  -- a maps span(M·Ω) into itself by linearity
  have h_span : ∀ y ∈ Submodule.span ℂ (M.orbit Ω), a y ∈ Submodule.span ℂ (M.orbit Ω) := by
    intro y hy
    have hmem : ∀ z ∈ M.orbit Ω, a z ∈ Submodule.span ℂ (M.orbit Ω) := h_orbit
    have hzero : a 0 ∈ Submodule.span ℂ (M.orbit Ω) := by simp
    have hadd : ∀ u v, a u ∈ Submodule.span ℂ (M.orbit Ω) → a v ∈ Submodule.span ℂ (M.orbit Ω) →
                a (u + v) ∈ Submodule.span ℂ (M.orbit Ω) := by
      intro u v hu hv; simp only [map_add]; exact Submodule.add_mem _ hu hv
    have hsmul : ∀ (c : ℂ) u, a u ∈ Submodule.span ℂ (M.orbit Ω) →
                 a (c • u) ∈ Submodule.span ℂ (M.orbit Ω) := by
      intro c u hu; simp only [ContinuousLinearMap.map_smul]; exact Submodule.smul_mem _ c hu
    -- Use span induction
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hy
    · exact hmem
    · exact hzero
    · intro u v _ _ hu hv; exact hadd u v hu hv
    · intro c u _ hu; exact hsmul c u hu
  -- Use continuity: a maps closure into closure
  -- Since a(S) ⊆ S for S = span(M·Ω), we have a(closure(S)) ⊆ closure(a(S)) ⊆ closure(S)
  let S := Submodule.span ℂ (M.orbit Ω)
  -- Step 1: a '' closure(S) ⊆ closure(a '' S) by continuity
  have step1 : a '' closure (S : Set H) ⊆ closure (a '' (S : Set H)) :=
    image_closure_subset_closure_image a.continuous
  -- Step 2: a '' S ⊆ S, so closure(a '' S) ⊆ closure(S)
  have h_image_sub : a '' (S : Set H) ⊆ (S : Set H) := by
    intro z hz
    obtain ⟨y, hy, rfl⟩ := hz
    exact h_span y hy
  have step2 : closure (a '' (S : Set H)) ⊆ closure (S : Set H) :=
    closure_mono h_image_sub
  -- Combine: a '' closure(S) ⊆ closure(S)
  have combined : a '' closure (S : Set H) ⊆ closure (S : Set H) := step1.trans step2
  -- x ∈ closure(S), so a x ∈ a '' closure(S) ⊆ closure(S)
  -- topologicalClosure_coe is definitional: ↑S.topologicalClosure = closure ↑S
  -- So S.topologicalClosure membership is the same as closure ↑S membership
  simp only [← SetLike.mem_coe, Submodule.topologicalClosure_coe] at hx ⊢
  exact combined ⟨x, hx, rfl⟩

/-! ### Relationship between cyclic and separating -/

/-- Key theorem: Ω is separating for M if and only if Ω is cyclic for M' (the commutant).
    This is a fundamental result in Tomita-Takesaki theory. -/
theorem separating_iff_cyclic_commutant (Ω : H) :
    M.IsSeparating Ω ↔ M.commutant.IsCyclic Ω := by
  constructor
  · -- If Ω is separating for M, it is cyclic for M'
    intro hsep
    -- The key insight: if x ⊥ M'·Ω, then for all b ∈ M', ⟨x, bΩ⟩ = 0
    -- Define a_x ∈ M'' = M by ⟨a_x Ω, ξ⟩ = ⟨x, ξ⟩ for ξ ∈ M'·Ω
    -- Then a_x Ω = x, but also a_x = 0 by density argument, so x = 0
    unfold IsCyclic cyclicSubspace
    sorry
  · -- If Ω is cyclic for M', it is separating for M
    intro hcyc a ha haΩ
    -- If aΩ = 0, then for all b ∈ M', ⟨aΩ, bΩ⟩ = 0
    -- But ⟨aΩ, bΩ⟩ = ⟨Ω, a†bΩ⟩ = ⟨Ω, ba†Ω⟩ (since a ∈ M, b ∈ M' commute)
    -- Since M'·Ω is dense, a†Ω = 0, and by similar argument a = 0
    sorry

/-- Cyclic for M implies separating for M' -/
theorem cyclic_implies_separating_commutant (Ω : H) (h : M.IsCyclic Ω) :
    M.commutant.IsSeparating Ω := by
  rw [separating_iff_cyclic_commutant]
  simp only [commutant_commutant]
  exact h

/-- Separating for M implies cyclic for M' -/
theorem separating_implies_cyclic_commutant (Ω : H) (h : M.IsSeparating Ω) :
    M.commutant.IsCyclic Ω :=
  (separating_iff_cyclic_commutant M Ω).mp h

/-! ### Standard form -/

/-- A von Neumann algebra is in standard form if there exists a cyclic-separating vector -/
def IsStandardForm : Prop :=
  ∃ Ω : H, M.IsCyclicSeparating Ω

/-- For standard form, the commutant also has the same cyclic-separating vector -/
theorem standard_form_commutant (Ω : H) (h : M.IsCyclicSeparating Ω) :
    M.commutant.IsCyclicSeparating Ω := by
  constructor
  · exact M.separating_implies_cyclic_commutant Ω h.2
  · exact M.cyclic_implies_separating_commutant Ω h.1

/-- The standard form is symmetric: if (M, H, Ω) is standard, so is (M', H, Ω) -/
theorem standard_form_symmetric (Ω : H) (h : M.IsCyclicSeparating Ω) :
    M.commutant.IsCyclicSeparating Ω :=
  M.standard_form_commutant Ω h

end VonNeumannAlgebra

/-! ### Faithful states and cyclic representations -/

namespace VonNeumannAlgebra

variable (M : VonNeumannAlgebra H)

/-- A state on M given by a unit vector -/
structure VectorState (M : VonNeumannAlgebra H) where
  vec : H
  norm_one : ‖vec‖ = 1

/-- The state functional ω(a) = ⟨Ω, aΩ⟩ -/
def VectorState.functional (ω : VectorState M) (a : H →L[ℂ] H) (_ : a ∈ M) : ℂ :=
  @inner ℂ H _ ω.vec (a ω.vec)

/-- A vector state is positive: ω(a*a) ≥ 0 -/
theorem VectorState.positive (ω : VectorState M) (a : H →L[ℂ] H) (_ha : a ∈ M) :
    0 ≤ (@inner ℂ H _ ω.vec ((ContinuousLinearMap.adjoint a ∘L a) ω.vec)).re := by
  simp only [ContinuousLinearMap.coe_comp', Function.comp_apply]
  have h : @inner ℂ H _ ω.vec ((ContinuousLinearMap.adjoint a) (a ω.vec)) =
           @inner ℂ H _ (a ω.vec) (a ω.vec) := by
    exact ContinuousLinearMap.adjoint_inner_right a ω.vec (a ω.vec)
  rw [h]
  exact inner_self_nonneg (𝕜 := ℂ) (x := a ω.vec)

/-- A vector state is faithful if ω(a*a) = 0 implies a = 0 -/
def VectorState.IsFaithful (ω : VectorState M) : Prop :=
  ∀ a ∈ M, @inner ℂ H _ ω.vec ((ContinuousLinearMap.adjoint a ∘L a) ω.vec) = 0 → a = 0

/-- A faithful vector state has a separating vector -/
theorem VectorState.faithful_implies_separating (ω : VectorState M) (hf : ω.IsFaithful) :
    M.IsSeparating ω.vec := by
  intro a ha haΩ
  apply hf a ha
  simp only [ContinuousLinearMap.coe_comp', Function.comp_apply, haΩ, map_zero, inner_zero_right]

/-- A separating vector gives a faithful state -/
theorem separating_implies_faithful (Ω : H) (hΩ : ‖Ω‖ = 1) (hsep : M.IsSeparating Ω) :
    (⟨Ω, hΩ⟩ : VectorState M).IsFaithful := by
  intro a ha hinner
  simp only [ContinuousLinearMap.coe_comp', Function.comp_apply] at hinner
  have h : @inner ℂ H _ Ω ((ContinuousLinearMap.adjoint a) (a Ω)) =
           @inner ℂ H _ (a Ω) (a Ω) := ContinuousLinearMap.adjoint_inner_right a Ω (a Ω)
  rw [h] at hinner
  have haΩ : a Ω = 0 := by
    rw [← inner_self_eq_zero (𝕜 := ℂ)]
    exact hinner
  exact hsep a ha haΩ

end VonNeumannAlgebra

/-! ### Projections in von Neumann algebras -/

namespace VonNeumannAlgebra

variable (M : VonNeumannAlgebra H)

/-- A projection in M is a self-adjoint idempotent element -/
structure Projection (M : VonNeumannAlgebra H) where
  op : H →L[ℂ] H
  mem : op ∈ M
  idem : op ∘L op = op
  selfadj : ContinuousLinearMap.adjoint op = op

/-- The zero projection -/
def Projection.zero : Projection M where
  op := 0
  mem := M.toStarSubalgebra.zero_mem
  idem := by ext x; simp only [ContinuousLinearMap.coe_comp', Function.comp_apply,
    ContinuousLinearMap.zero_apply]
  selfadj := by simp only [map_zero]

/-- The identity projection -/
def Projection.one : Projection M where
  op := 1
  mem := M.toStarSubalgebra.one_mem
  idem := by ext x; simp only [ContinuousLinearMap.coe_comp', Function.comp_apply,
    ContinuousLinearMap.one_apply]
  selfadj := ContinuousLinearMap.adjoint_id

/-- Projections are positive operators -/
theorem Projection.positive (p : Projection M) (x : H) :
    0 ≤ (@inner ℂ H _ x (p.op x)).re := by
  have key : @inner ℂ H _ x (p.op x) = @inner ℂ H _ (p.op x) (p.op x) := by
    -- Step 1: p(px) = px since p² = p
    have idem_app : p.op (p.op x) = p.op x := by
      have := congrFun (congrArg DFunLike.coe p.idem) x
      simp only [ContinuousLinearMap.coe_comp', Function.comp_apply] at this
      exact this
    -- Step 2: Use p = p† then adjoint_inner_right
    -- ⟨x, p(px)⟩ = ⟨x, p†(px)⟩ = ⟨px, px⟩
    have step2 : @inner ℂ H _ x (p.op (p.op x)) =
                 @inner ℂ H _ x ((ContinuousLinearMap.adjoint p.op) (p.op x)) := by
      congr 2
      exact p.selfadj.symm
    calc @inner ℂ H _ x (p.op x)
        = @inner ℂ H _ x (p.op (p.op x)) := by rw [idem_app]
      _ = @inner ℂ H _ x ((ContinuousLinearMap.adjoint p.op) (p.op x)) := step2
      _ = @inner ℂ H _ (p.op x) (p.op x) := ContinuousLinearMap.adjoint_inner_right p.op x (p.op x)
  rw [key]
  exact inner_self_nonneg (𝕜 := ℂ)

/-- The range of a projection is a closed subspace -/
def Projection.rangeSubmodule (p : Projection M) : Submodule ℂ H :=
  LinearMap.range p.op.toLinearMap

/-- The kernel of a projection is a closed subspace -/
def Projection.kerSubmodule (p : Projection M) : Submodule ℂ H :=
  LinearMap.ker p.op.toLinearMap

/-- Support projection of a vector -/
def supportProjection (Ω : H) : Submodule ℂ H :=
  Submodule.span ℂ {Ω}

end VonNeumannAlgebra
